# Generated by Django 6.0.1 on 2026-01-29 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FARMER', 'Farmer'), ('RICE_MILL', 'Rice Mill'), ('CUSTOMER', 'Customer')], default='FARMER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('avatar_icon', models.CharField(default='👨🌾', max_length=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('selfie_image', models.ImageField(blank=True, null=True, upload_to='verification/selfies/')),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='verification/ids/')),
                ('farm_image', models.ImageField(blank=True, help_text='For Farmers: Farmland/Crop photo', null=True, upload_to='verification/farms/')),
                ('mill_image', models.ImageField(blank=True, help_text='For Rice Mills: Machinery/Premises photo', null=True, upload_to='verification/mills/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FarmerProfile',
        ),
    ]
