# Generated by Django 6.0.1 on 2026-02-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_delete_farmerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='farm_image',
            new_name='farm_photo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='id_card_image',
            new_name='id_proof',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='mill_image',
            new_name='mill_photo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='selfie_image',
            new_name='user_photo',
        ),
    ]
