# Generated by Django 6.0.1 on 2026-02-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='item_photo',
        ),
    ]
